### ISSUE TITLE
Unhandled 'error' event at "Basics: PUT"

### ISSUE THREAD

**Issue by szymex73** [workshopper/levelmeup#70] opened 2016-07-20 13:22 UTC
I was running my code in "levelmeup run program.js" and it worked properly,
but in "levelmeup verify program.js" it was throwing this error:
`Verifying "Basics: PUT"...

events.js:85
      throw er; // Unhandled 'error' event
            ^
OpenError: IO error: lock /tmp/~levelmeup_1_5093/LOCK: Resource temporarily unavailable
    at /usr/local/lib/node_modules/levelmeup/node_modules/level/node_modules/level-packager/node_modules/levelup/lib/levelup.js:119:34
    at /usr/local/lib/node_modules/levelmeup/node_modules/level/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16`

I tried command with mine code, and the official solution from page, it always dumps this error

Nodejs - v6.3.0
Node - v0.12.7

**Comment by martinheidegger** [comment] 2016-12-29 07:49
Without your `program.js` this is a little of a guess but this seems like a duplicate of #42 and should be solved with #92. #42 is still open so I will close this issue. Please reopen if that was done prematurely.

**Closed by martinheidegger** 2016-12-29 07:49 UTC
