### ISSUE TITLE
Wrong problem description for Exercise 3

### ISSUE THREAD

**Issue by DCrow** [workshopper/levelmeup#117] opened 2017-06-20 15:30 UTC
This description is wrong:
```javascript
Your module could look like:
module.exports = function (databaseDir, callback) {
    var result = []
    // your code...
    result.push()
    // more code...
    callback(result)
}
```
Original description, asks that `callback(result)` is invoked using one parameter, but it actually requires two `callback(error, result)`

Description should be:
```javascript
Your module could look like:
module.exports = function (databaseDir, callback) {
    var result = []
    // your code...
    result.push()
    // more code...
    callback(error, result)
}
```

**Comment by martinheidegger** [comment] 2017-11-24 04:17
Duplicate of #96

**Closed by martinheidegger** 2017-11-24 04:17 UTC
